Vagrant.configure("2") do |config|

  # Changement de la box
  config.vm.box = "centos/7"
  config.vm.network "forwarded_port", guest: 80, host: 1235
  config.vm.hostname = "miage"
  
  # Modification du provider pour VMWARE
  config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "1024"
      v.gui = false
    end

  # update des commandes pour yum package manager
  # Installation de nginx à la création de la VM
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y epel-release
    yum  update
    yum install -y nginx
    systemctl restart nginx
  SHELL
end
