Vagrant.configure("2") do |config|
    
    # Definition de la VM web
    config.vm.define "web" do |web|
        web.vm.box = "ubuntu/bionic64"
        web.vm.network "forwarded_port", guest: 80, host: 1235
        web.vm.hostname = "miage-web"
        web.vm.network "private_network", ip: "192.168.33.10"

        # Provider virtualBox
        web.vm.provider "virtualbox" do |v|
            v.gui = false
        end

        # Enable provisioning with a shell script
        web.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y nginx
          systemctl restart nginx
        SHELL
    end

    # Definition de la VM app
    config.vm.define "app" do |app|
        app.vm.box = "ubuntu/bionic64"
        app.vm.network "forwarded_port", guest: 80, host: 1236
        app.vm.hostname = "miage-app"
        app.vm.network "private_network", ip: "192.168.33.20"
        
        # Provider virtualBox
        app.vm.provider "virtualbox" do |v|
            v.gui = false
        end
      
        # Enable provisioning with a shell script
        app.vm.provision "shell", inline: <<-SHELL
          apt-get update
          apt-get install -y nginx
          systemctl restart nginx
        SHELL
    end
  end
  