version: '3.1'

services:
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@okabi-tech.com
      - PGADMIN_DEFAULT_PASSWORD=test
    restart: always