
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 1235
  config.vm.hostname = "miage"
  config.vm.network "private_network", ip: "192.168.33.10"

  # Enable provisioning with a shell script
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    systemctl restart nginx
  SHELL
end
